namespace NodeJS {
  interface ProcessEnv {
    MONGODB_URI: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    LINKEDIN_CLIENT_ID: string;
    LINKEDIN_CLIENT_SECRET: string;
    MICROSOFT_TENANT_ID: string;
    MICROSOFT_CLIENT_ID: string;
    MICROSOFT_CLIENT_SECRET: string;
    MICROSOFT_VIDEO_INDEXER_CLIENT_ID: string;
    MICROSOFT_VIDEO_INDEXER_CLIENT_SECRET: string;
    MICROSOFT_COOKIE_KEY: string;
    MICROSOFT_COOKIE_IV: string;
    SWAGGER_USERNAME: string;
    SWAGGER_PASSWORD: string;
    JWT_SECRET: string;
    JWT_EXPIRATION_TIME: string;
    PORT: string;
    DOMAIN: string;
    AUTH_CALLBACK_SECRET: string;
    AUTH_CALLBACK_URL: string;
    PASSWORD_RESET_URL: string;
    INVITATION_URL: string;
    BASE_URL: string;
    AZURE_SUBSCRIPTION_ID: string;
    AZURE_VIDEO_INDEXER_ACCOUNT_ID: string;
    AZURE_VIDEO_INDEXER_LOCATION: string;
    AZURE_VIDEO_INDEXER_ACCOUNT_NAME: string;
    AZURE_VIDEO_INDEXER_RESOURCE_GROUP_NAME: string;
    AZURE_VIDEO_INDEXER_API_KEY: string;
    AZURE_STORAGE_CONNECTION_STRING: string;
    AZURE_COMMUNICATION_SERVICES_CONNECTION_STRING: string;
    AZURE_SERVICE_BUS_CONNECTION_STRING: string;
    AZURE_OPENAI_BASE_PATH: string;
    AZURE_OPENAI_API_KEY: string;
    AZURE_OPENAI_API_VERSION: string;
    AZURE_OPENAI_DEPLOYMENT: string;
    MIXPANEL_PROJECT_TOKEN: string;
  }
}
